### ISSUE TITLE
Game Crashes With Shader: `No uniform block exists with name: ubo_ChunkFadeDatas`

### ISSUE THREAD

**Issue by atchimgripo** [kolgushev/Pixel-Perfect-B#5]
**Describe the bug**
Game crashes without explanation

**To Reproduce**
1. Open minecraft 1.20.2
2. Select pixel perfect shaders
3. It crashes
(Using iris 1.6.10 + AMD RX550)

**Expected behavior**
Game not crashing.

**Screenshots**
Yeah it doesn't even shows up

**Desktop (please complete the following information):**
 - Loader and loader version [Iris 1.6.10]
 - Minecraft version [Minecraft 1.20.2]
 - Graphics Card [RX550 4GIGS]
 - OS: [Windows 10]

**Comment by kolgushev** [comment]
Do you have a crash log or an error message on the launcher? Knowing that would be very helpful for debugging.

**Comment by atchimgripo** [comment]
sorry for closing the issue, missclick, here's the crash report anyway
[crash-2023-10-23_12.04.26-client.txt](https://github.com/kolgushev/Pixel-Perfect-B/files/13072398/crash-2023-10-23_12.04.26-client.txt)

**Comment by kolgushev** [comment]
You're fine, I'll add a note about Iris to the shaders when I have time

**Comment by kolgushev** [comment]
Sorry for taking so long to get back to you.
The issue seems to be with your "chunks fade in" mod.
The reason other shaders work seems to be because they use an older GLSL version which is more supported and probably has the bug, but I'm not sure.
If I find a workaround, I'll try to include it in a patch to the shader. For now, if your game still crashes even after disabling the fog fade mod, please create a new issue and I'll see what I can do about it.
